name: Publish Artifact

on: 
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: 'release'       
  AZURE_WEBAPP_PACKAGE_PATH: '.'   # Defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with: 
          node-version: "14.x"
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: npm install, build and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: 'Deploy to Azure Webapp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      